FROM almalinux:9
RUN yum install telnet -y
CMD [ "sleep","20000" ]

# As it's alma OS, many commands won't be working.Commands which you need can be given in this debug and push to hub.
#pull from them when it's required. pulling them in k8